config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get 'sessions/new'

  get 'users/new'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get     '/info',   to: 'calculators#info'

  resources :calculators do
    member do
      post 'roll'
      patch 'undo'
      patch 'clear'
      patch 'remove_player'
      get 'load'
      patch 'add_player'
    end
  end
end

app/models/calculator.rb
require 'random_name_generator'

class Calculator < ApplicationRecord
  validates :name, presence: true
  has_many :players, dependent: :destroy
  has_many :rolls, dependent: :destroy
  belongs_to :user

  attr_accessor :player_name

  def run_scenario(attacker, defender, winner, ratio, number)
    attacker = players.find_by(name: attacker)
    defender = players.find_by(name: defender)
    attacker.input_roll(attacker, defender, winner, ratio, number)
    defender.input_roll(attacker, defender, winner, ratio, number)
    streak(attacker)
    rolls.build(attacker: attacker.name, defender: defender.name, winner: winner, ratio: ratio, number: number)
  end

  # def calculate_undo(player1_name, player2_name, die1, die2)
  #   player1 = players.find_by(name: player1_name)
  #   player2 = players.find_by(name: player2_name)
  #   luck = (die2.to_f / die1.to_f).round(2)

  #   player1.one_to_three_wins -= 1  if(die1 == 1 && die2 == 3)
  #   player2.three_to_one_losses -= 1  if(die1 == 1 && die2 == 3)
  #   player1.update_win(luck: luck, undo: true)
  #   player2.update_loss(luck: luck, undo: true)
  # end

  # def undo_roll
  #   if rolls.count > 0
  #     roll = rolls.last

  #     calculate_undo(roll.player1, roll.player2, roll.die1, roll.die2)
  #     roll.destroy
  #   else
  #     puts "No rolls yet\n"
  #   end
  # end

  def streak(player)
    if streak_holder == player.name
      player.update(streak_count: player.streak_count + 1)
      if player.streak_count >= player.streak
        player.update(streak: player.streak_count + 1)
      end
    else
      player.update(streak_count: 0)
    end
    update(streak_holder: player.name)
  end

  def sort_players
    return players.sort_by(&:luck).reverse! if players
    nil
  end

   def destroy_players
     self.players.destroy_all
   end

   def destroy_rolls
     self.rolls.destroy_all
   end
end

app/controllers/calculators_controller.rb
class CalculatorsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:roll]

  def index
    @calculator = self
  end

  def new
    @calculator = Calculator.new
  end

  def show
    @calculator = Calculator.find(params[:id])
    @roll = @calculator.rolls.build
  end

  def create
    @calculator = Calculator.new(name: params[:calculator][:name], user: current_user)
    if @calculator.save
      flash[:success] = "Game created"
      redirect_to @calculator
    else
      render 'new'
    end
  end

  def add_player
    @calculator = Calculator.find(params[:id])
    name = params[:calculator][:player_name]
    player = @calculator.players.find_by(name: name)

    if !player || @calculator.players.count == 0
      flash[:success] = "Player #{name} added"
      player = @calculator.players.build(name: name, wins: 0, losses: 0, ratio: 0, luck: 0,
        luckwins: 0, lucklosses: 0, one_to_three_wins: 0, three_to_one_wins: 0, stats: [])
      player.set_streak_to_zero
      player.initialize_roll_count
    else
      flash[:warning] = "#{name} already exists"
    end

    @calculator.save

    redirect_to calculator_path
  end

  def remove_player
    @calculator = Calculator.find(params[:id])
    player = @calculator.players.find_by(name: params[:name]).destroy
    flash[:danger] = "#{player.name} removed"
    @calculator.save

    redirect_to @calculator
  end

  def destroy
    @calculator = Calculator.find(params[:id])
    if @calculator.destroy
      redirect_to calculators_path, flash: { success: "#{@calculator.name} deleted" }
    else
      render :index, flash: { error: "#{@calculator.name} could not be deleted" }
    end
  end

  def clear
    @calculator = Calculator.find(params[:id])
    @calculator.destroy_players
    @calculator.destroy_rolls

    redirect_to @calculator
  end

  def roll
    @calculator = Calculator.find(params[:id])
    @calculator.run_scenario(params[:attacker], params[:defender], params[:winner],
    params[:dice_ratio], params[:number_wins].to_i)
    @calculator.save

    respond_to do |format|
      format.html do
        render :show
      end
      format.json {

      }
    end
  end

  def undo
    @calculator = Calculator.find(params[:id])
    @calculator.undo_roll
    @calculator.save

    redirect_to @calculator
  end
end

app/views/calculators/index.html.slim
- content_for :header_right
  = link_to "Logout", logout_path, method: :delete, class: 'white-link'
.container.pb-5
  .flex.justify-center
    h1.games-title Games
    = link_to image_tag('new-game', class: 'new-game'), new_calculator_path
  .game-container
    - current_user.calculators.each do |c|
      .card.game-panel
        h3.game-title = "#{c.name}"
        = link_to "View", c, class: 'btn btn-outline-success mt-3'
        = link_to "Delete", c, method: :delete, class: 'btn btn-outline-danger mt-3',
          data: { confirm: "Are you sure you want to delete this game?"}

app/views/calculators/info.slim
.container.mb-5
  h1.display-6.mb-3 Welcome to our luck calculator for the Risk board game!
  .flex.justify-center
    img src='https://gazettereview.com/wp-content/uploads/2017/03/Risk-Featured-e1488483112745.jpg' alt='Card image cap' style='border-radius: 10px; width: 400px;'
  .mt-3
    p Have you ever played Risk with your friends and felt like you were overwhemingly unlucky (or lucky)
        with your rolls? Well now is your chance to prove it! We have created a simple tool that allows you to keep track
        of each roll as you play the game, and displays stats showing how lucky or unlucky each player was!
    p It works by calculating adjusted wins and adjusted losses that account for how many dice were rolled and not just a
      straight win or loss. For instance, if Bob beats Jim in a 1 to 3 roll, he was a lot more lucky then if it had been
      a 1 to 1 roll. Therefore his adjusted wins will go up by 3 while his normal wins only goes up by 1.
    p To get started, create a game, add players, and input the rolls!

app/views/calculators/new.slim
.container
  h1 Create game
  .small-container
    = form_for(@calculator) do |f|
      = f.label :name
      = f.text_field :name, class: 'form-control'
      .flex.justify-center
        = f.submit "Create game", class: "btn btn-outline-primary mt-3"

app/views/calculators/show.html.slim
.container
  .row
    .col-md-6
      .card.panel.mt-4
        .card-body
          h5.card-title.text-center Roll
          = react_component("RollInput", { players: @calculator.players.map(&:name), id: @calculator.id })
    .col-md-6
      .card.panel.mt-4
        .card-body
          h5.card-title.text-center Log
          table.fl-table
            .flex
              .list-rolls
                - @calculator.rolls.each do |roll|
                  p.roll-message = roll.to_s
              = button_to "Undo Roll", undo_calculator_path, method: :patch, class: 'btn btn-outline-warning undo-roll mt-2'
  .row
    .col-md-12
      .mt-4.table-wrapper
        h1.stats.text-center.p-2.m-0 Stats
        table.table
          thead
            tr.text-center.thead-primary
              th Player
              th Wins
              th Losses
              th Adj Wins
              th Adj Losses
              th Ratio
              th Luck
              th Delete
          tbody
            - @calculator.sort_players&.each do |p|
              tr.text-center
                td = p.name
                td = p.wins
                td = p.losses
                td = p.luckwins&.round(2)
                td = p.lucklosses&.round(2)
                td = p.ratio&.round(2)
                td = p.luck&.round(2)
                td = button_to "Remove", remove_player_calculator_path(name: p.name), method: :patch, class: 'btn btn-outline-danger m-1',
                    data: { confirm: "Are you sure you want to remove this player?"}
        tr = form_for @calculator, url: {action: 'add_player'} do |f|
          .add-player-box
            = f.text_field :player_name, class: 'form-control', placeholder: "player name"
            = f.submit "Add Player", class: "btn btn-outline-info ml-2"
  / .row.chart.mt-5
  /   .col-md-12
  /     h5.stats.text-center Luck vs. Time
  /     == line_chart( @calculator.players.map { |player| { name: player.name, data: player.stats_with_index } } )
  / .row
  /   .col-md-5.chart
  /     h5.stats.text-center 1-3 Wins
  /     == pie_chart (@calculator.players.map { |player| [player.name, player.one_to_three_wins]})
  /   .col-md-5.chart
  /     h5.stats.text-center 3-1 losses
  /     == pie_chart( @calculator.players.map { |player| [player.name, player.three_to_one_wins]} )
  / .row.chart
  /   .col-md-12
  /     h5.stats.text-center Total Rolls compared to Wins
  /     == column_chart( @calculator.players.map { |player| { name: player.name, data: player.rolls_and_wins } } )
  / .row
  /   .col-md-12.chart
  /     h5.stats.text-center Win Streaks
  /     == bar_chart (@calculator.players.map { |player| [player.name, player.streak]})
  .flex.justify-center.mb-5
    = button_to "Clear Session", clear_calculator_path, method: :patch, class: 'btn btn-outline-warning m-1',
      data: { confirm: "Are you sure you want clear all the data?"}
    = button_to "Delete Game", calculator_path(@calculator), method: :delete, class: 'btn btn-outline-danger m-1',
      data: { confirm: "Are you sure you want to delete this game? The data will be erased forever"}