config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get 'sessions/new'

  get 'users/new'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get     '/info',   to: 'calculators#info'

  resources :calculators do
    member do
      post 'roll'
      patch 'undo'
      patch 'clear'
      patch 'remove_player'
      get 'load'
      patch 'add_player'
    end
  end
end

app/views/layouts/_footer.html.slim
.page-footer.footer.footer-layout
  span.navbar-text.p-2 Copyright © 2019 Josh McLeod & Jeremy Walton

app/views/layouts/_header.html.slim
nav.navbar.navbar-dark.bg-primary
  a.navbar-brand href='/info' Risk Luck Tracker
  #navbarSupportedContent
    = link_to "Risk", calculators_path, class: 'white-link'
    == yield :header_right

app/views/layouts/_imports.html.slim
= csrf_meta_tags
= csp_meta_tag
meta name="viewport" content="width=device-width, initial-scale=1"
script src='https://code.jquery.com/jquery-3.2.1.slim.min.js' integrity='sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN' crossorigin='anonymous'
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'https://js.pusher.com/5.0/pusher.min.js', 'data-turbolinks-track': 'reload'
= javascript_pack_tag 'pusher', 'data-turbolinks-track': 'reload'
= javascript_pack_tag 'chart', 'data-turbolinks-track': 'reload'
= javascript_pack_tag 'chartkick', 'data-turbolinks-track': 'reload'

/ script src='https://code.jquery.com/jquery-3.2.1.slim.min.js' integrity='sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN' crossorigin='anonymous'
/ script src='https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js' integrity='sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q' crossorigin='anonymous'
/ script src="https://www.google.com/jsapi"
/ script src='chart.js'
/ script src='chartkick.js'

app/views/layouts/application.html.slim
doctype html
html
  head
    title Risk Luck Tracker
    = render 'layouts/imports'
  body
    = render 'layouts/header'
    - flash.each do |message_type, message|
      .alert class="alert-#{message_type}" = message
    == yield
    = render 'layouts/footer'